[2025-04-03 13:47:08] INFO    Writing the log to tests/logs/pipeline_upload/pipeline_upload-20250403_1347.log
[2025-04-03 13:47:08] INFO    ========== BEGIN PIPELINE_UPLOAD WORKFLOW ==========
[2025-04-03 13:47:08] INFO    ZenodoUploadWorkflow(dpath_pipeline=tests/data/zenodo.zip, zenodo_api=<nipoppy.zenodo_api.ZenodoAPI object at 0x108223350>, zenodo_id=zenodo.123456, fpath_layout=None, verbose=False, dry_run=False)
[2025-04-03 13:47:08] ERROR   Error while running nipoppy
Traceback (most recent call last):
  File "/Users/mathdugre/oss/nipoppy/nipoppy/cli.py", line 29, in handle_exception
    yield workflow
  File "/Users/mathdugre/oss/nipoppy/nipoppy/cli.py", line 424, in pipeline_upload
    workflow.run()
  File "/Users/mathdugre/oss/nipoppy/nipoppy/workflows/base.py", line 184, in run
    self.run_setup()
  File "/Users/mathdugre/oss/nipoppy/nipoppy/workflows/base.py", line 326, in run_setup
    self.layout.validate()
  File "/Users/mathdugre/oss/nipoppy/nipoppy/layout.py", line 261, in validate
    raise FileNotFoundError(
FileNotFoundError: Dataset does not follow expected directory structure. Missing 18 paths: ['tests/bids', 'tests/derivatives', 'tests/sourcedata', 'tests/sourcedata/tabular', 'tests/sourcedata/imaging', 'tests/sourcedata/imaging/downloads', 'tests/sourcedata/imaging/pre_reorg', 'tests/sourcedata/imaging/post_reorg', 'tests/code', 'tests/pipelines', 'tests/containers', 'tests/scratch', 'tests/scratch/pybids_db', 'tests/scratch/work', 'tests/tabular', 'tests/tabular/assessments', 'tests/global_config.json', 'tests/manifest.tsv']
[2025-04-03 13:47:59] INFO    Writing the log to tests/logs/pipeline_upload/pipeline_upload-20250403_1347.log
[2025-04-03 13:47:59] INFO    ========== BEGIN PIPELINE_UPLOAD WORKFLOW ==========
[2025-04-03 13:47:59] INFO    ZenodoUploadWorkflow(dpath_pipeline=tests/data/zenodo.zip, zenodo_api=<nipoppy.zenodo_api.ZenodoAPI object at 0x113501f10>, zenodo_id=zenodo.123456, fpath_layout=None, verbose=False, dry_run=False)
[2025-04-03 13:47:59] ERROR   Error while running nipoppy
Traceback (most recent call last):
  File "/Users/mathdugre/oss/nipoppy/nipoppy/cli.py", line 29, in handle_exception
    yield workflow
  File "/Users/mathdugre/oss/nipoppy/nipoppy/cli.py", line 424, in pipeline_upload
    workflow.run()
  File "/Users/mathdugre/oss/nipoppy/nipoppy/workflows/base.py", line 184, in run
    self.run_setup()
  File "/Users/mathdugre/oss/nipoppy/nipoppy/workflows/base.py", line 326, in run_setup
    self.layout.validate()
  File "/Users/mathdugre/oss/nipoppy/nipoppy/layout.py", line 261, in validate
    raise FileNotFoundError(
FileNotFoundError: Dataset does not follow expected directory structure. Missing 18 paths: ['tests/bids', 'tests/derivatives', 'tests/sourcedata', 'tests/sourcedata/tabular', 'tests/sourcedata/imaging', 'tests/sourcedata/imaging/downloads', 'tests/sourcedata/imaging/pre_reorg', 'tests/sourcedata/imaging/post_reorg', 'tests/code', 'tests/pipelines', 'tests/containers', 'tests/scratch', 'tests/scratch/pybids_db', 'tests/scratch/work', 'tests/tabular', 'tests/tabular/assessments', 'tests/global_config.json', 'tests/manifest.tsv']
